[tool.poetry]
name = "simple-gpt-news-filter"
version = "0.1.0"
description = ""
authors = ["kahilav2 <kahilav4@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
